name: Test and Deploy
on: push

jobs:
  test:
    name: Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install Deno
        uses: denoland/setup-deno@v1
      - name: Install npm dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm test
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            dist
            schema/schema.json
  deploy:
    name: Deploy
    needs: test
    # if: github.ref == 'refs/heads/main'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kaleidoshare
          entrypoint: server/index.ts
          import-map: server/deno.jsonc
